version: '3'

services:
  db:
    container_name: zfr_postgres
    image: qaprosoft/postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  rabbitmq:
    container_name: zfr_rabbitmq
    image: qaprosoft/rabbitmq:latest
    ports:
      - 15672:15672
      - 61613:61613
      - 5672:5672
    volumes:
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      - RABBITMQ_DEFAULT_USER=qpsdemo
      - RABBITMQ_DEFAULT_PASS=qpsdemo
    restart: always
  redis:
    container_name: zfr_redis
    image: redis:5.0.5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - 6379:6379
    restart: always
  elasticsearch:
    container_name: zfr_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: always
  logstash:
    container_name: zfr_logstash
    image: docker.elastic.co/logstash/logstash:6.3.1
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./config/mapping.json:/mapping.json:ro
    restart: always
    depends_on:
      - elasticsearch
  zafira:
    container_name: zfr_zafira_back_end
    image: qaprosoft/zafira:4.1.86
    # build: .
    volumes:
      - ./assets:/opt/assets
    ports:
      - 8080:8080
    env_file:
      - zafira-properties.env
    depends_on:
      - "db"
      - "rabbitmq"
      - "redis"
    restart: always
  zafira-ui:
    container_name: zfr_zafira_ui
    image: qaprosoft/zafira-ui:1.32
    ports:
      - 80:80
    env_file:
      - zafira-properties.env
    depends_on:
      - "zafira"
volumes:
  postgres:
