# Usage:
#   docker-compose -p zalenium up -d --force-recreate --build
version: '3'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium:3"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - C:\AutoInfra_DockerVolumes\Zalenium\Videos:/home/seluser/videos
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- "/usr/bin/docker:/usr/bin/docker"
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Asia/Kolkata"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false

    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
#      - zalenium_http_proxy=YOUR_HTTP_PROXY
#      - zalenium_https_proxy=YOUR_HTTPS_PROXY
#      - zalenium_no_proxy=NO_PROXY_LOCAL_HOSTS

#  selenium:
#    image: "elgalu/selenium:3.141"
